package com.qatestlab.Units;

public enum UnitType {
    ELFWIZARD, ELFARCHER, ELFWARRIOR,
    HUMANWIZARD, HUMANARCHER, HUMANWARRIOR,
    ORCSHAMAN, ORCARCHER, ORCHOBLIN,
    NECROMANCER, HUNTER, ZOMBIE
}
